# Application
spring.application.name=minibank-backend


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/minibank}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true


server.port=${SERVER_PORT:8080}


app.security.jwt.secret=${JWT_SECRET:change_this_secret_key_to_long_random_string_123456789}
app.security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:120}


logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}
logging.level.org.hibernate.SQL=${HIBERNATE_LOG_LEVEL:INFO}